org: abdennour
app: contac-us
service: contact-us
frameworkVersion: '3'
provider:
  name: aws
  stage: local
  runtime: nodejs14.x
  region: us-west-2

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
functions:
  sendContact:
    handler: src/handler.sendContact
    description: send contact information for contact us form
    events:
      - httpApi:
          path: /v1/contactus
          method: POST
          # cors: true