name: Deploy Serverless

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install NPM dependencies
      run: npm ci
    - name: 'Create env file'
      run: |
        touch .env
        echo username=${{ secrets.EMAIL_USERNAME }} >> .env
        echo password=${{ secrets.EMAIL_PASS }} >> .env
        echo receivingEmail=${{ secrets.EMAIL_RECEIVER }} >> .env
    - name: serverless deploy
      uses: serverless/github-action@v3
      with:
        args: deploy --stage dev
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}